"""Assertion tests for pipeline/classify_titles.py.

Every example named in the classifier spec appears here, plus regression cases
found while auditing build/title_residual.parquet.  Run with:

    uv run python -m career_clean.families.family_tests
"""
from career_clean.families.classify import classify_title, normalize
from career_clean.families.taxonomy import FAMILIES, NEVER_LAND, SENIORITY
from transition_network.common import SOC_MAJOR


def fam(s):
    return classify_title(s)['family']


def sen(s):
    return classify_title(s)['seniority']


def flg(s):
    return classify_title(s)['flags']


def conf(s):
    return classify_title(s)['confidence']


def run():
    # ------------------------------------------------------------ taxonomy contract
    for code, (_label, _grp, soc) in FAMILIES.items():
        assert soc is None or soc in SOC_MAJOR, f"anchor {soc} for {code} is not a SOC major group"
    assert NEVER_LAND <= set(FAMILIES), NEVER_LAND - set(FAMILIES)
    for code in ('student', 'intern', 'volunteer_board', 'not_working', 'unclassified'):
        assert code in NEVER_LAND, code
    # ---------------------------------------------------------------- contract
    for t in ('teacher', 'ceo', '', 'zzzqqq', 'owner'):
        r = classify_title(t)
        assert r['family'] in FAMILIES, r
        assert r['seniority'] in SENIORITY, r
        assert isinstance(r['flags'], list), r
        assert r['confidence'] in ('high', 'low'), r

    # ------------------------------------------------------------ normalisation
    assert normalize('Sr. Marketing Manager')[0] == 'senior marketing manager'
    assert normalize('V.P. of Sales')[0] == 'vice president of sales'
    assert normalize('Asst. Mgr')[0] == 'assistant manager'
    assert normalize('Program Coord.')[0] == 'program coordinator'
    assert normalize('Dir. of Ops')[0] == 'director of operations'
    assert normalize('Sales & Marketing')[0] == 'sales and marketing'
    assert normalize('Teacher at Lincoln High')[0] == 'teacher'
    assert normalize('Barista @ Starbucks')[0] == 'barista'
    assert normalize("Teacher's Aide")[0] == 'teacher aide'
    assert 'part time' in normalize('Cashier (part-time)')[2]
    assert fam('Cashier (part-time)') == 'retail'
    assert 'part_time' in flg('Cashier (part-time)')
    assert fam('stay-at-home mom') == 'not_working'
    assert fam('attorney at law') == 'legal_attorney'

    # ---------------------------------------------------------------- seniority
    assert sen('intern') == 'intern'
    assert sen('marketing intern') == 'intern'
    assert flg('marketing intern') == ['intern']
    assert fam('marketing intern') == 'marketing'
    assert sen('summer analyst') == 'intern'
    assert sen('co-op engineer') == 'intern'
    assert sen('research fellow') == 'entry'
    assert fam('postdoctoral fellow') == 'higher_ed_faculty'
    assert sen('junior developer') == 'entry'
    assert sen('program coordinator') == 'entry'
    assert sen('management trainee') == 'entry'
    assert sen('entry level analyst') == 'entry'
    assert sen('assistant buyer') == 'entry'
    assert sen('assistant professor') == 'mid'
    assert fam('assistant professor') == 'higher_ed_faculty'
    assert sen('associate professor of english') == 'mid'
    assert sen('associate attorney') == 'mid'
    assert fam('associate attorney') == 'legal_attorney'
    assert sen('executive assistant') == 'mid'
    assert fam('executive assistant') == 'admin_support'
    assert sen('administrative assistant') == 'mid'
    assert sen('executive assistant to the ceo') == 'mid'
    assert sen('senior software engineer') == 'senior'
    assert sen('lead designer') == 'senior'
    assert sen('principal software engineer') == 'senior'
    assert sen('staff software engineer') == 'senior'
    assert sen('staff accountant') in ('entry', 'mid')
    assert fam('staff accountant') == 'finance_accounting'
    assert sen('sales manager') == 'manager'
    assert sen('production supervisor') == 'manager'
    assert sen('head of school') == 'director'
    assert sen('director of operations') == 'director'
    assert sen('head of people') == 'director'
    assert sen('vice president') == 'vp'
    assert sen('vp of sales') == 'vp'
    assert sen('svp marketing') == 'vp'
    assert sen('evp operations') == 'vp'
    assert sen('senior vice president') == 'vp'
    assert sen('chief executive officer') == 'c_suite'
    assert sen('cfo') == 'c_suite'
    assert sen('coo') == 'c_suite'
    assert sen('chief technology officer') == 'c_suite'
    assert sen('chief marketing officer') == 'c_suite'
    assert sen('president') == 'c_suite'
    assert sen('chairman') == 'c_suite'
    assert sen('chancellor') == 'c_suite'
    assert sen('provost') == 'c_suite'
    assert fam('provost') == 'higher_ed_staff'
    assert sen('executive director') == 'c_suite'
    assert fam('executive director') == 'executive'
    assert sen('owner') == 'owner'
    assert sen('founder') == 'owner'
    assert sen('co-founder') == 'owner'
    assert sen('proprietor') == 'owner'
    assert sen('partner') == 'owner'
    assert fam('partner') == 'general_management'
    assert sen('managing partner') == 'owner'
    assert sen('analyst') == 'mid'
    assert sen('assistant manager') == 'manager'
    assert sen('associate director') == 'director'
    assert sen('assistant vice president') == 'vp'
    assert sen('product owner') == 'mid'
    assert sen('human resources business partner') == 'mid'
    assert fam('human resources business partner') == 'hr_recruiting'

    # ----------------------------------------------- writing / editing / media
    assert fam('writer') == 'writing_editing'
    assert fam('author') == 'writing_editing'
    assert fam('copywriter') == 'writing_editing'
    assert fam('editor') == 'writing_editing'
    assert fam('editorial assistant') == 'writing_editing'
    assert fam('publisher') == 'writing_editing'
    assert fam('proofreader') == 'writing_editing'
    assert fam('content writer') == 'writing_editing'
    assert fam('technical writer') == 'writing_editing'
    assert fam('grant writer') == 'writing_editing'
    assert fam('blogger') == 'writing_editing'
    assert fam('managing editor') == 'writing_editing'
    assert fam('columnist') == 'journalism_media'
    assert fam('content strategist') == 'marketing'
    assert fam('content marketing manager') == 'marketing'
    assert fam('journalist') == 'journalism_media'
    assert fam('reporter') == 'journalism_media'
    assert fam('correspondent') == 'journalism_media'
    assert fam('news anchor') == 'journalism_media'
    assert fam('news producer') == 'journalism_media'
    assert fam('podcast producer') == 'journalism_media'
    assert fam('broadcast engineer') == 'journalism_media'
    assert fam('producer') == 'journalism_media'
    assert fam('video producer') == 'design_ux'
    assert fam('film producer') == 'design_ux'
    assert fam('videographer') == 'design_ux'
    assert fam('photographer') == 'design_ux'
    assert fam('animator') == 'design_ux'
    assert fam('motion graphics designer') == 'design_ux'
    assert fam('video editor') == 'design_ux'

    # --------------------------------------------------------- pr / marketing
    assert fam('public relations manager') == 'pr_communications'
    assert fam('pr coordinator') == 'pr_communications'
    assert fam('communications specialist') == 'pr_communications'
    assert fam('corporate communications director') == 'pr_communications'
    assert fam('media relations manager') == 'pr_communications'
    assert fam('public affairs officer') == 'pr_communications'
    assert fam('public information officer') == 'pr_communications'
    assert fam('press secretary') == 'pr_communications'
    assert fam('speechwriter') == 'pr_communications'
    assert fam('communications') == 'pr_communications'
    assert fam('director of communications') == 'pr_communications'
    assert fam('communications director') == 'pr_communications'
    assert fam('marketing manager') == 'marketing'
    assert fam('manager of marketing') == 'marketing'
    assert fam('senior marketing manager') == 'marketing'
    assert fam('brand manager') == 'marketing'
    assert fam('digital marketing specialist') == 'marketing'
    assert fam('seo specialist') == 'marketing'
    assert fam('social media manager') == 'marketing'
    assert fam('growth marketing manager') == 'marketing'
    assert fam('demand generation manager') == 'marketing'
    assert fam('advertising manager') == 'marketing'
    assert fam('media planner') == 'marketing'
    assert fam('account planner') == 'marketing'
    assert fam('brand ambassador') == 'marketing'
    assert fam('account executive') == 'sales'
    assert fam('account manager') == 'sales'
    assert fam('advertising account executive') == 'marketing'
    assert fam('public relations account executive') == 'pr_communications'

    # ------------------------------------------------------------ design / arts
    assert fam('graphic designer') == 'design_ux'
    assert fam('ux designer') == 'design_ux'
    assert fam('ui designer') == 'design_ux'
    assert fam('product designer') == 'design_ux'
    assert fam('art director') == 'design_ux'
    assert fam('creative director') == 'design_ux'
    assert fam('web designer') == 'design_ux'
    assert fam('illustrator') == 'design_ux'
    assert fam('artist') == 'arts_performance'
    assert fam('musician') == 'arts_performance'
    assert fam('singer') == 'arts_performance'
    assert fam('actor') == 'arts_performance'
    assert fam('actress') == 'arts_performance'
    assert fam('performer') == 'arts_performance'
    assert fam('dancer') == 'arts_performance'
    assert fam('composer') == 'arts_performance'
    assert fam('painter') == 'arts_performance'
    assert fam('sculptor') == 'arts_performance'
    assert fam('choreographer') == 'arts_performance'
    assert fam('dj') == 'arts_performance'
    assert fam('teaching artist') == 'other_education'
    assert fam('audio engineer') == 'arts_performance'
    assert fam('sound engineer') == 'arts_performance'

    # ------------------------------------------------------ museums / libraries
    assert fam('librarian') == 'museum_library'
    assert fam('library assistant') == 'museum_library'
    assert fam('archivist') == 'museum_library'
    assert fam('archives technician') == 'museum_library'
    assert fam('curator') == 'museum_library'
    assert fam('curatorial assistant') == 'museum_library'
    assert fam('museum educator') == 'museum_library'
    assert fam('collections manager') == 'museum_library'
    assert fam('gallery director') == 'museum_library'
    assert fam('school librarian') == 'museum_library'
    assert fam('historian') == 'research'
    assert fam('registrar') == 'higher_ed_staff'

    # -------------------------------------------------------------- education
    assert fam('teacher') == 'teaching_k12'
    assert fam('substitute teacher') == 'teaching_k12'
    assert fam('paraprofessional') == 'teaching_k12'
    assert fam('instructional aide') == 'teaching_k12'
    assert fam('teacher assistant') == 'teaching_k12'
    assert fam('school counselor') == 'teaching_k12'
    assert fam('esl teacher') == 'teaching_k12'
    assert fam('english teacher') == 'teaching_k12'
    assert fam('history teacher') == 'teaching_k12'
    assert fam('special education teacher') == 'teaching_k12'
    assert fam('principal') == 'school_admin'
    assert sen('principal') == 'director'
    assert fam('school principal') == 'school_admin'
    assert fam('assistant principal') == 'school_admin'
    assert sen('assistant principal') == 'director'
    assert fam('superintendent of schools') == 'school_admin'
    assert fam('school administrator') == 'school_admin'
    assert fam('professor') == 'higher_ed_faculty'
    assert fam('assistant professor of history') == 'higher_ed_faculty'
    assert fam('associate professor') == 'higher_ed_faculty'
    assert fam('adjunct professor') == 'higher_ed_faculty'
    assert fam('adjunct faculty') == 'higher_ed_faculty'
    assert fam('lecturer') == 'higher_ed_faculty'
    assert fam('adjunct instructor') == 'higher_ed_faculty'
    assert fam('postdoctoral researcher') == 'higher_ed_faculty'
    assert fam('visiting scholar') == 'higher_ed_faculty'
    assert fam('teaching fellow') == 'higher_ed_faculty'
    assert fam('instructor') == 'other_education'
    assert fam('teaching assistant') == 'other_education'
    assert flg('teaching assistant') == ['ta']
    assert fam('graduate teaching assistant') == 'other_education'
    assert 'ta' in flg('graduate teaching assistant')
    assert fam('graduate assistant') == 'student'
    assert fam('graduate research assistant') == 'student'
    assert fam('admissions counselor') == 'higher_ed_staff'
    assert fam('academic advisor') == 'higher_ed_staff'
    assert fam('student affairs coordinator') == 'higher_ed_staff'
    assert fam('residence life coordinator') == 'higher_ed_staff'
    assert fam('resident advisor') == 'higher_ed_staff'
    assert fam('financial aid counselor') == 'higher_ed_staff'
    assert fam('dean of students') == 'higher_ed_staff'
    assert fam('enrollment specialist') == 'higher_ed_staff'
    assert fam('career services coordinator') == 'higher_ed_staff'
    assert fam('study abroad advisor') == 'higher_ed_staff'
    assert fam('tutor') == 'other_education'
    assert fam('corporate trainer') == 'other_education'
    assert fam('instructional designer') == 'other_education'
    assert fam('curriculum developer') == 'other_education'
    assert fam('athletic coach') == 'personal_care_fitness'
    assert fam('head coach') == 'personal_care_fitness'
    assert fam('personal trainer') == 'personal_care_fitness'
    assert fam('fitness instructor') == 'personal_care_fitness'

    # --------------------------------------------------- research / data / tech
    assert fam('research assistant') == 'research'
    assert fam('research associate') == 'research'
    assert fam('research analyst') == 'research'
    assert fam('researcher') == 'research'
    assert fam('research fellow') == 'research'
    assert fam('research coordinator') == 'research'
    assert fam('policy researcher') == 'research'
    assert fam('market research analyst') == 'research'
    assert fam('ux researcher') == 'research'
    assert fam('research scientist') == 'science_lab'
    assert fam('data analyst') == 'data_analytics'
    assert fam('data scientist') == 'data_analytics'
    assert fam('business intelligence developer') == 'data_analytics'
    assert fam('analytics manager') == 'data_analytics'
    assert fam('statistician') == 'data_analytics'
    assert fam('machine learning engineer') == 'data_analytics'
    assert fam('software engineer') == 'software'
    assert fam('software developer') == 'software'
    assert fam('programmer') == 'software'
    assert fam('web developer') == 'software'
    assert fam('front end developer') == 'software'
    assert fam('back end engineer') == 'software'
    assert fam('full stack developer') == 'software'
    assert fam('devops engineer') == 'software'
    assert fam('sre') == 'software'
    assert fam('qa engineer') == 'software'
    assert fam('test engineer') == 'software'
    assert fam('mobile developer') == 'software'
    assert fam('information technology specialist') == 'it_support'
    assert fam('systems administrator') == 'it_support'
    assert fam('network engineer') == 'it_support'
    assert fam('help desk technician') == 'it_support'
    assert fam('desktop support specialist') == 'it_support'
    assert fam('technical support specialist') == 'it_support'
    assert fam('it specialist') == 'it_support'
    assert fam('cloud administrator') == 'it_support'
    assert fam('security analyst') == 'it_support'
    assert fam('cybersecurity analyst') == 'it_support'
    assert fam('database administrator') == 'it_support'
    assert fam('systems analyst') == 'it_support'
    assert fam('product manager') == 'product_management'
    assert fam('product owner') == 'product_management'
    assert fam('mechanical engineer') == 'engineering'
    assert fam('civil engineer') == 'engineering'
    assert fam('electrical engineer') == 'engineering'
    assert fam('chemical engineer') == 'engineering'
    assert fam('structural engineer') == 'engineering'
    assert fam('industrial engineer') == 'engineering'
    assert fam('process engineer') == 'engineering'
    assert fam('manufacturing engineer') == 'engineering'
    assert fam('design engineer') == 'engineering'
    assert fam('project engineer') == 'engineering'
    assert fam('field engineer') == 'engineering'
    assert fam('hardware engineer') == 'engineering'
    assert fam('engineer') == 'engineering'
    assert fam('engineering manager') == 'engineering'
    assert fam('sales engineer') == 'sales'
    assert fam('scientist') == 'science_lab'
    assert fam('chemist') == 'science_lab'
    assert fam('biologist') == 'science_lab'
    assert fam('lab technician') == 'science_lab'
    assert fam('laboratory manager') == 'science_lab'
    assert fam('geologist') == 'science_lab'
    assert fam('microbiologist') == 'science_lab'
    assert fam('clinical research coordinator') == 'science_lab'

    # ----------------------------------------------------- finance / law / gov
    assert fam('accountant') == 'finance_accounting'
    assert fam('cpa') == 'finance_accounting'
    assert fam('controller') == 'finance_accounting'
    assert fam('bookkeeper') == 'finance_accounting'
    assert fam('auditor') == 'finance_accounting'
    assert fam('financial analyst') == 'finance_accounting'
    assert fam('finance manager') == 'finance_accounting'
    assert fam('tax associate') == 'finance_accounting'
    assert fam('payroll specialist') == 'finance_accounting'
    assert fam('treasury analyst') == 'finance_accounting'
    assert fam('accounts payable clerk') == 'finance_accounting'
    assert fam('accounts receivable specialist') == 'finance_accounting'
    assert fam('billing specialist') == 'finance_accounting'
    assert fam('financial advisor') == 'banking_insurance'
    assert fam('wealth manager') == 'banking_insurance'
    assert fam('investment analyst') == 'banking_insurance'
    assert fam('personal banker') == 'banking_insurance'
    assert fam('loan officer') == 'banking_insurance'
    assert fam('mortgage loan originator') == 'banking_insurance'
    assert fam('underwriter') == 'banking_insurance'
    assert fam('insurance agent') == 'banking_insurance'
    assert fam('claims adjuster') == 'banking_insurance'
    assert fam('bank teller') == 'banking_insurance'
    assert fam('broker') == 'banking_insurance'
    assert fam('realtor') == 'real_estate'
    assert fam('real estate agent') == 'real_estate'
    assert fam('real estate broker') == 'real_estate'
    assert fam('property manager') == 'real_estate'
    assert fam('leasing consultant') == 'real_estate'
    assert fam('attorney') == 'legal_attorney'
    assert fam('lawyer') == 'legal_attorney'
    assert fam('general counsel') == 'legal_attorney'
    assert fam('associate attorney') == 'legal_attorney'
    assert fam('judge') == 'legal_attorney'
    assert fam('magistrate') == 'legal_attorney'
    assert fam('prosecutor') == 'legal_attorney'
    assert fam('public defender') == 'legal_attorney'
    assert fam('paralegal') == 'legal_support'
    assert fam('legal assistant') == 'legal_support'
    assert fam('legal secretary') == 'legal_support'
    assert fam('law clerk') == 'legal_support'
    assert fam('litigation support specialist') == 'legal_support'
    assert fam('contracts administrator') == 'legal_support'
    assert fam('policy analyst') == 'government_policy'
    assert fam('legislative assistant') == 'government_policy'
    assert fam('city council member') == 'government_policy'
    assert fam('city manager') == 'government_policy'
    assert fam('government affairs director') == 'government_policy'
    assert fam('foreign service officer') == 'government_policy'
    assert fam('intelligence analyst') == 'government_policy'
    assert fam('urban planner') == 'government_policy'
    assert fam('program analyst') == 'government_policy'

    # ---------------------------------------- nonprofit / social / clergy / med
    assert fam('program coordinator') == 'nonprofit_program'
    assert fam('program director') == 'nonprofit_program'
    assert fam('program associate') == 'nonprofit_program'
    assert fam('program manager') == 'project_program_mgmt'
    assert fam('community organizer') == 'nonprofit_program'
    assert fam('outreach coordinator') == 'nonprofit_program'
    assert fam('development director') == 'nonprofit_program'
    assert fam('development associate') == 'nonprofit_program'
    assert fam('grants manager') == 'nonprofit_program'
    assert fam('fundraiser') == 'nonprofit_program'
    assert fam('director of advancement') == 'nonprofit_program'
    assert fam('philanthropy officer') == 'nonprofit_program'
    assert fam('donor relations manager') == 'nonprofit_program'
    assert fam('volunteer coordinator') == 'nonprofit_program'
    assert fam('business development manager') == 'sales'
    assert fam('software development manager') == 'software'
    assert fam('social worker') == 'social_services'
    assert fam('case manager') == 'social_services'
    assert fam('caseworker') == 'social_services'
    assert fam('mental health counselor') == 'social_services'
    assert fam('therapist') == 'social_services'
    assert fam('psychotherapist') == 'social_services'
    assert fam('residential counselor') == 'social_services'
    assert fam('victim advocate') == 'social_services'
    assert fam('pastor') == 'clergy'
    assert fam('minister') == 'clergy'
    assert fam('priest') == 'clergy'
    assert fam('rabbi') == 'clergy'
    assert fam('chaplain') == 'clergy'
    assert fam('youth pastor') == 'clergy'
    assert fam('worship leader') == 'clergy'
    assert fam('missionary') == 'clergy'
    assert fam('registered nurse') == 'healthcare_clinical'
    assert fam('licensed practical nurse') == 'healthcare_clinical'
    assert fam('cna') == 'healthcare_clinical'
    assert fam('physician') == 'healthcare_clinical'
    assert fam('dentist') == 'healthcare_clinical'
    assert fam('pharmacist') == 'healthcare_clinical'
    assert fam('physical therapist') == 'healthcare_clinical'
    assert fam('occupational therapist') == 'healthcare_clinical'
    assert fam('speech language pathologist') == 'healthcare_clinical'
    assert fam('physician assistant') == 'healthcare_clinical'
    assert fam('nurse practitioner') == 'healthcare_clinical'
    assert fam('paramedic') == 'healthcare_clinical'
    assert fam('resident physician') == 'healthcare_clinical'
    assert fam('veterinarian') == 'healthcare_clinical'
    assert fam('dental hygienist') == 'healthcare_clinical'
    assert fam('radiologic technologist') == 'healthcare_clinical'
    assert fam('medical assistant') == 'healthcare_support'
    assert fam('medical receptionist') == 'healthcare_support'
    assert fam('patient care coordinator') == 'healthcare_support'
    assert fam('medical scribe') == 'healthcare_support'
    assert fam('medical biller') == 'healthcare_support'
    assert fam('pharmacy technician') == 'healthcare_support'
    assert fam('caregiver') == 'healthcare_support'
    assert fam('home health aide') == 'healthcare_support'
    assert fam('phlebotomist') == 'healthcare_support'
    assert fam('practice manager') == 'healthcare_support'
    assert fam('hospital administrator') == 'healthcare_support'
    assert fam('physical therapist assistant') == 'healthcare_support'

    # ------------------------------------- military / protective / service jobs
    assert fam('united states army') == 'military'
    assert fam('navy officer') == 'military'
    assert fam('air force') == 'military'
    assert fam('marine corps') == 'military'
    assert fam('coast guard') == 'military'
    assert fam('soldier') == 'military'
    assert fam('sergeant') == 'military'
    assert fam('captain') == 'military'
    assert fam('petty officer') == 'military'
    assert fam('national guard') == 'military'
    assert fam('rotc cadet') == 'military'
    assert fam('police officer') == 'protective_services'
    assert fam('deputy sheriff') == 'protective_services'
    assert fam('detective') == 'protective_services'
    assert fam('firefighter') == 'protective_services'
    assert fam('security officer') == 'protective_services'
    assert fam('security guard') == 'protective_services'
    assert fam('correctional officer') == 'protective_services'
    assert fam('probation officer') == 'protective_services'
    assert fam('loss prevention associate') == 'protective_services'
    assert fam('server') == 'hospitality_food'
    assert fam('waitress') == 'hospitality_food'
    assert fam('bartender') == 'hospitality_food'
    assert fam('barista') == 'hospitality_food'
    assert fam('hostess') == 'hospitality_food'
    assert fam('line cook') == 'hospitality_food'
    assert fam('executive chef') == 'hospitality_food'
    assert fam('dishwasher') == 'hospitality_food'
    assert fam('catering manager') == 'hospitality_food'
    assert fam('event coordinator') == 'hospitality_food'
    assert fam('wedding planner') == 'hospitality_food'
    assert fam('banquet server') == 'hospitality_food'
    assert fam('hotel manager') == 'hospitality_food'
    assert fam('concierge') == 'hospitality_food'
    assert fam('housekeeper') == 'hospitality_food'
    assert fam('tour guide') == 'hospitality_food'
    assert fam('flight attendant') == 'hospitality_food'
    assert fam('cashier') == 'retail'
    assert fam('sales associate') == 'retail'
    assert fam('retail sales associate') == 'retail'
    assert fam('store manager') == 'retail'
    assert fam('shift supervisor') == 'retail'
    assert fam('keyholder') == 'retail'
    assert fam('merchandiser') == 'retail'
    assert fam('stocker') == 'retail'
    assert fam('team member') == 'retail'
    assert fam('crew member') == 'retail'
    assert fam('customer service representative') == 'customer_service'
    assert fam('customer support specialist') == 'customer_service'
    assert fam('call center representative') == 'customer_service'
    assert fam('customer success manager') == 'customer_service'
    assert fam('sales representative') == 'sales'
    assert fam('inside sales representative') == 'sales'
    assert fam('territory manager') == 'sales'
    assert fam('sales consultant') == 'sales'
    assert fam('regional sales manager') == 'sales'
    assert fam('vp of sales') == 'sales'
    assert fam('nanny') == 'personal_care_fitness'
    assert fam('babysitter') == 'personal_care_fitness'
    assert fam('childcare provider') == 'personal_care_fitness'
    assert fam('hairstylist') == 'personal_care_fitness'
    assert fam('cosmetologist') == 'personal_care_fitness'
    assert fam('esthetician') == 'personal_care_fitness'
    assert fam('massage therapist') == 'personal_care_fitness'
    assert fam('barber') == 'personal_care_fitness'
    assert fam('lifeguard') == 'personal_care_fitness'
    assert fam('dog walker') == 'personal_care_fitness'
    assert fam('truck driver') == 'trades_logistics'
    assert fam('warehouse associate') == 'trades_logistics'
    assert fam('forklift operator') == 'trades_logistics'
    assert fam('machinist') == 'trades_logistics'
    assert fam('mechanic') == 'trades_logistics'
    assert fam('maintenance technician') == 'trades_logistics'
    assert fam('electrician') == 'trades_logistics'
    assert fam('plumber') == 'trades_logistics'
    assert fam('carpenter') == 'trades_logistics'
    assert fam('welder') == 'trades_logistics'
    assert fam('construction foreman') == 'trades_logistics'
    assert fam('quality control inspector') == 'trades_logistics'
    assert fam('logistics coordinator') == 'trades_logistics'
    assert fam('supply chain manager') == 'trades_logistics'
    assert fam('purchasing agent') == 'trades_logistics'
    assert fam('delivery driver') == 'trades_logistics'
    assert fam('pilot') == 'trades_logistics'
    assert fam('mail carrier') == 'trades_logistics'
    assert fam('janitor') == 'trades_logistics'
    assert fam('plant manager') == 'trades_logistics'

    # ---------------------------------------- business / admin / mgmt / owners
    assert fam('administrative assistant') == 'admin_support'
    assert fam('office manager') == 'admin_support'
    assert fam('receptionist') == 'admin_support'
    assert fam('secretary') == 'admin_support'
    assert fam('data entry clerk') == 'admin_support'
    assert fam('administrative coordinator') == 'admin_support'
    assert fam('scheduler') == 'admin_support'
    assert fam('human resources manager') == 'hr_recruiting'
    assert fam('recruiter') == 'hr_recruiting'
    assert fam('talent acquisition specialist') == 'hr_recruiting'
    assert fam('benefits administrator') == 'hr_recruiting'
    assert fam('compensation analyst') == 'hr_recruiting'
    assert fam('people operations manager') == 'hr_recruiting'
    assert fam('hr generalist') == 'hr_recruiting'
    assert fam('head of people') == 'hr_recruiting'
    assert fam('payroll manager') == 'finance_accounting'
    assert fam('management consultant') == 'consulting'
    assert fam('strategy consultant') == 'consulting'
    assert fam('associate consultant') == 'consulting'
    assert fam('consultant') == 'consulting'
    assert conf('consultant') == 'low'
    assert fam('business analyst') == 'business_analysis'
    assert fam('operations analyst') == 'business_analysis'
    assert fam('analyst') == 'business_analysis'
    assert conf('analyst') == 'low'
    assert fam('management analyst') == 'business_analysis'
    assert fam('process improvement specialist') == 'business_analysis'
    assert fam('quality analyst') == 'business_analysis'
    assert fam('project manager') == 'project_program_mgmt'
    assert fam('project coordinator') == 'project_program_mgmt'
    assert fam('scrum master') == 'project_program_mgmt'
    assert fam('implementation manager') == 'project_program_mgmt'
    assert fam('general manager') == 'general_management'
    assert fam('operations manager') == 'general_management'
    assert fam('manager') == 'general_management'
    assert conf('manager') == 'low'
    assert fam('assistant manager') == 'general_management'
    assert fam('branch manager') == 'general_management'
    assert fam('district manager') == 'general_management'
    assert fam('regional manager') == 'general_management'
    assert fam('team lead') == 'general_management'
    assert fam('supervisor') == 'general_management'
    assert fam('director of operations') == 'general_management'
    assert fam('vice president') == 'general_management'
    assert fam('chief of staff') == 'general_management'
    assert fam('business manager') == 'general_management'
    assert fam('facilities manager') == 'trades_logistics'
    assert fam('director') == 'general_management'
    assert conf('director') == 'low'
    assert fam('specialist') == 'business_analysis'
    assert conf('specialist') == 'low'
    assert fam('coordinator') == 'admin_support'
    assert conf('coordinator') == 'low'
    assert fam('associate') == 'business_analysis'
    assert conf('associate') == 'low'
    assert fam('ceo') == 'executive'
    assert fam('chief executive officer') == 'executive'
    assert fam('president') == 'executive'
    assert fam('cfo') == 'executive'
    assert fam('chief operating officer') == 'executive'
    assert fam('chief technology officer') == 'executive'
    assert fam('chief information officer') == 'executive'
    assert fam('chief revenue officer') == 'executive'
    assert fam('executive director') == 'executive'
    assert fam('managing director') == 'executive'
    assert fam('chairman') == 'executive'
    assert fam('owner') == 'founder_owner'
    assert fam('business owner') == 'founder_owner'
    assert fam('founder') == 'founder_owner'
    assert fam('co-founder') == 'founder_owner'
    assert fam('proprietor') == 'founder_owner'
    assert fam('self-employed') == 'founder_owner'
    assert fam('freelance') == 'founder_owner'
    assert flg('freelance') == ['self_employed']
    assert fam('freelance writer') == 'writing_editing'
    assert flg('freelance writer') == ['self_employed']
    assert fam('independent contractor') == 'founder_owner'
    assert fam('entrepreneur') == 'founder_owner'
    assert fam('founder and ceo') == 'founder_owner'
    assert sen('founder and ceo') == 'owner'

    # ---------------------------------------------- translation, non-employment
    assert fam('translator') == 'translation_language'
    assert fam('interpreter') == 'translation_language'
    assert fam('localization manager') == 'translation_language'
    assert fam('asl interpreter') == 'translation_language'
    assert fam('student') == 'student'
    assert fam('graduate student') == 'student'
    assert fam('undergraduate') == 'student'
    assert fam('mba candidate') == 'student'
    assert fam('phd candidate') == 'student'
    assert fam('doctoral candidate') == 'student'
    assert fam('law student') == 'student'
    assert fam('medical student') == 'student'
    assert fam('student assistant') == 'student'
    assert fam('student worker') == 'student'
    assert fam('work study student') == 'student'
    assert fam('student ambassador') == 'student'
    assert fam('orientation leader') == 'student'
    assert fam('intern') == 'intern'
    assert fam('summer intern') == 'intern'
    assert fam('internship') == 'intern'
    assert fam('software engineer intern') == 'software'
    assert sen('software engineer intern') == 'intern'
    assert fam('volunteer') == 'volunteer_board'
    assert fam('board member') == 'volunteer_board'
    assert fam('board of directors') == 'volunteer_board'
    assert fam('trustee') == 'volunteer_board'
    assert fam('advisory board member') == 'volunteer_board'
    assert fam('member') == 'volunteer_board'
    assert fam('committee member') == 'volunteer_board'
    assert fam('mentor') == 'volunteer_board'
    assert fam('volunteer tutor') == 'other_education'
    assert 'volunteer' in flg('volunteer tutor')
    assert fam('retired') == 'not_working'
    assert fam('stay at home mom') == 'not_working'
    assert fam('stay at home dad') == 'not_working'
    assert fam('homemaker') == 'not_working'
    assert fam('career break') == 'not_working'
    assert fam('sabbatical') == 'not_working'
    assert fam('unemployed') == 'not_working'
    assert fam('seeking opportunities') == 'not_working'
    assert fam('open to work') == 'not_working'
    assert fam('n/a') == 'unclassified'
    assert fam('none') == 'unclassified'
    assert fam('-') == 'unclassified'

    # ------------------------------------------------ head-noun / priority rules
    assert fam('marketing manager') == 'marketing'
    assert fam('manager of marketing') == 'marketing'
    assert fam('director of communications') == 'pr_communications'
    assert fam('communications director') == 'pr_communications'
    assert fam('engineering manager') == 'engineering'
    assert fam('software engineering manager') == 'software'
    assert fam('vp of sales') == 'sales'
    assert sen('vp of sales') == 'vp'
    assert fam('head of people') == 'hr_recruiting'
    assert fam('writer/editor') == 'writing_editing'
    assert fam('server/bartender') == 'hospitality_food'
    assert fam('owner/operator') == 'founder_owner'
    assert fam('president/ceo') == 'executive'
    assert fam('sales and marketing manager') == 'sales'
    assert fam('marketing and communications director') == 'marketing'

    print('all assertions passed')


if __name__ == '__main__':
    run()
