"""Assemble results/*.json into results/benchmark.md (the tables the docs cite).

    uv run python -m archetype_methods.bench
"""

from __future__ import annotations

import json

import numpy as np

from . import common as C
from . import framework as F
from . import metrics as M


def _load(name):
    p = C.RESULTS / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else {}


def main():
    ded, mix, llm, ind = _load("deductive"), _load("mixed"), _load("llm"), _load("inductive")
    lines = ["# Benchmark tables", "",
             "Generated by `bench.py` from `results/*.json`. Gold: 400 hand-labeled roles, "
             "100 per person-support band (A >= 1000, B 100-999, C 20-99, D 5-19 holders).", "",
             "## Labeled methods (deductive, mixed, LLM)", "",
             "cov = share of gold roles given a label (not abstain). strict = primary matches. "
             "lenient = primary or secondary matches. w = person-weighted. assigned = strict accuracy "
             "among non-abstained. F1 = macro over ten labels. fit = strict accuracy on strong / weak / none gold.", "",
             "| method | cov | strict | lenient | strict w | assigned | macro F1 | strong / weak / none |",
             "|---|---|---|---|---|---|---|---|"]
    allres = {}
    for src in (ded, llm, mix):
        for nm, s in src.items():
            allres[nm] = s
    order = sorted(allres, key=lambda n: -allres[n]["acc_strict"])
    for nm in order:
        lines.append(M.summary_row(allres[nm]))
    lines += ["", "## Per-label F1 (strict), best methods", ""]
    labels = list(F.KEYS) + [F.NONE_KEY]
    lines.append("| method | " + " | ".join(labels) + " |")
    lines.append("|---|" + "---|" * len(labels))
    for nm in order[:8]:
        f = allres[nm]["f1_by_label"]
        lines.append(f"| {nm} | " + " | ".join(f"{f[L]:.2f}" for L in labels) + " |")
    lines += ["", "## Strict accuracy by support band", "", "| method | A | B | C | D |", "|---|---|---|---|---|"]
    for nm in order[:8]:
        b = allres[nm]["acc_by_band"]
        lines.append(f"| {nm} | " + " | ".join(f"{b.get(k, float('nan')):.2f}" for k in "ABCD") + " |")
    lines += ["", "## Clusterings (inductive)", "",
              "AMI = adjusted mutual information with the gold archetype labels. recov cv = accuracy of "
              "the majority cluster-to-archetype map, 5-fold cross-validated over gold roles (in-sample in "
              "parentheses). SOC purity = person-weighted share of each cluster in its modal SOC major. "
              "eff k = exponentiated entropy of person-weighted cluster sizes. stability = ARI between two "
              "seeds.", "",
              "| clustering | k | roles | AMI | recov cv (in) | SOC purity | largest | eff k | stability |",
              "|---|---|---|---|---|---|---|---|---|"]
    for nm, s in ind.items():
        st = s.get("stability_ari")
        lines.append(f"| {nm} | {s['k']} | {s['n_roles']} | {s['ami_gold']:.3f} | {s['recoverability_cv']:.3f} "
                     f"({s['recoverability_insample']:.3f}) | {s['soc_purity_w']:.3f} | "
                     f"{s['largest_cluster_share_w']:.2f} | {s['effective_k_w']:.1f} | "
                     f"{'' if st is None else f'{st:.2f}'} |")
    # agreement matrix among the full-universe labeled methods
    assigns = {}
    for f in ("deductive_assignments", "mixed_assignments"):
        p = C.RESULTS / f"{f}.npy"
        if p.exists():
            assigns.update(np.load(p, allow_pickle=True).item())
    pick = [n for n in ("D1_lexicon_soc", "D2_seed_knn_f0.00", "D2p_prototype_f0.00", "D4_onet_bridge",
                        "M1b_embed_spread", "M2_mobility_spread", "M3_classifier", "M5_vote_D1_D2_M1b_M3")
            if n in assigns]
    if pick:
        t = C.load_roles()
        roles = t["role_canonical"].to_pylist()
        w = t["n_persons"].to_pylist()
        lines += ["", "## Agreement between methods on the whole universe (person-weighted Cohen's kappa)", "",
                  "| | " + " | ".join(pick) + " |", "|---|" + "---|" * len(pick)]
        for a in pick:
            row = []
            for b in pick:
                row.append("1.00" if a == b else f"{M.agreement(assigns[a], assigns[b], roles, w)['kappa']:.2f}")
            lines.append(f"| {a} | " + " | ".join(row) + " |")
        # population shares by method
        lines += ["", "## Person-weighted share of the universe per label", "",
                  "| method | " + " | ".join(labels + ["abstain"]) + " |", "|---|" + "---|" * (len(labels) + 1)]
        tot = sum(w)
        for a in pick:
            share = {L: 0.0 for L in labels + ["abstain"]}
            for rc, ww in zip(roles, w):
                share[assigns[a].get(rc, ("abstain", 0))[0]] += ww
            lines.append(f"| {a} | " + " | ".join(f"{share[L] / tot:.2f}" for L in labels + ["abstain"]) + " |")
    (C.RESULTS / "benchmark.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
