"""Certification title -> skills-domain taxonomy (audit R6).

Two layers, both value-keyed on the cleanlib-normalized title:

1. CURATED head: the top-400 raw titles by row frequency, classified by the
   local 27B (qwen3.8, 2026-09-01, delegated bulk pass) and adjudicated by the
   orchestrating session (fixes noted inline). First-wins on normalized-key
   collisions; the list is frequency-ordered so the dominant surface wins.
2. KEYWORD rules for the tail: ordered, first-match-wins, most-specific first.

This is a descriptive axis (method + confidence carried on every row), not a
calibrated jury: 'curated' rows are reviewed, 'keyword' rows are heuristic.
"""

from __future__ import annotations

from cleanlib import normalize

# id -> label
DOMAINS: dict[str, str] = {
    "pm": "Project management & agile",
    "fin": "Finance, accounting & licenses",
    "health": "Health & clinical",
    "it_cloud": "Cloud platforms",
    "it_sec": "Information security",
    "it_net": "IT, networking & support",
    "data": "Data, analytics & AI",
    "swdev": "Software development",
    "hr": "Human resources",
    "sales_mkt": "Sales, marketing & service",
    "edu": "Teaching & instruction",
    "trades": "Skilled trades & safety",
    "food": "Food service",
    "fitness": "Fitness & coaching",
    "legal": "Legal & compliance",
    "lang": "Language",
    "design": "Design & UX",
    "mgmt": "Leadership & business skills",
    "other": "Other / unclassified",
}

# (verbatim raw title, domain) — top-400 by frequency. Adjudicated fixes from
# the delegated pass: CPC -> health (medical coding, not software);
# Secret Security Clearance -> other (a clearance, not a skill cert);
# Professional Engineer / Engineer In Training -> trades (licensed engineering).
CURATED_RAW: tuple[tuple[str, str], ...] = (
    ("Project Management Professional (PMP)", "pm"),
    ("Certified Public Accountant", "fin"),
    ("Basic Life Support for Healthcare Providers (BLS)", "health"),
    ("Notary Public", "fin"),
    ("Registered Nurse", "health"),
    ("Series 7", "fin"),
    ("Basic Life Support (BLS)", "health"),
    ("AWS Certified Cloud Practitioner", "it_cloud"),
    ("Series 63", "fin"),
    ("CompTIA Security+", "it_sec"),
    ("Certified ScrumMaster (CSM)", "pm"),
    ("CPR/AED/First Aid", "health"),
    ("Microsoft Certified: Azure Fundamentals", "it_cloud"),
    ("Lean Six Sigma Green Belt", "pm"),
    ("Real Estate Broker/Sales Agent", "fin"),
    ("CompTIA A+", "it_net"),
    ("PMP", "pm"),
    ("Certified Scrum Product Owner (CSPO)", "pm"),
    ("Series 66", "fin"),
    ("Securities Industry Essentials (SIE)", "fin"),
    ("Foundations of Project Management", "pm"),
    ("CPR & AED", "health"),
    ("Pediatric Advanced Life Support (PALS)", "health"),
    ("CPA", "fin"),
    ("Six Sigma Green Belt", "pm"),
    ("Advanced Cardiovascular Life Support (ACLS)", "health"),
    ("SHRM - Certified Professional (SHRM-CP)", "hr"),
    ("Scrum Master Certified (SMC)", "pm"),
    ("CompTIA Network+", "it_net"),
    ("Professional Engineer (PE)", "trades"),
    ("Salesforce Certified Administrator (SCA)", "swdev"),
    ("Google Ads Search Certification", "sales_mkt"),
    ("Lean Six Sigma Yellow Belt", "pm"),
    ("AWS Certified Solutions Architect – Associate", "it_cloud"),
    ("Unconscious Bias", "hr"),
    ("The Six Morning Habits of High Performers", "mgmt"),
    ("Mental Health First Aid", "health"),
    ("Diversity, Equity and Inclusion in the Workplace Certificate", "hr"),
    ("Strategic Thinking", "mgmt"),
    ("Bloomberg Market Concepts", "fin"),
    ("CPR", "health"),
    ("Series 6", "fin"),
    ("Diversity, Inclusion, and Belonging", "hr"),
    ("Certified Information Systems Security Professional (CISSP)", "it_sec"),
    ("Adult and Pediatric First Aid/CPR/AED", "health"),
    ("Professional in Human Resources (PHR)", "hr"),
    ("Insurance Agent, Accident, Health, Life, Variable Life & Variable Annuities", "fin"),
    ("Foundations: Data, Data, Everywhere", "data"),
    ("ServSafe Manager", "food"),
    ("Google Analytics Individual Qualification", "sales_mkt"),
    ("Series 65", "fin"),
    ("Real Estate Broker", "fin"),
    ("Technical Support Fundamentals", "it_net"),
    ("Google Analytics Certification", "sales_mkt"),
    ("Confronting Bias: Thriving Across Our Differences", "hr"),
    ("Project Management", "pm"),
    ("Attorney", "legal"),
    ("Licensed Clinical Social Worker", "health"),
    ("Certified Associate in Project Management (CAPM)", "pm"),
    ("Agile Foundations", "pm"),
    ("Chartered Financial Analyst (CFA)", "fin"),
    ("Member", "other"),
    ("Project Initiation: Starting a Successful Project", "pm"),
    ("Developing Your Emotional Intelligence", "mgmt"),
    ("Life and Health Insurance License", "fin"),
    ("Certified Pharmacy Technician (CPhT)", "health"),
    ("Prosci® Certified Change Practitioner", "mgmt"),
    ("Lean Six Sigma Black Belt", "pm"),
    ("Google Analytics", "sales_mkt"),
    ("What Is Generative AI?", "data"),
    ("A+", "it_net"),
    ("PHR", "hr"),
    ("Social Media Marketing", "sales_mkt"),
    ("Hootsuite Platform Certification", "sales_mkt"),
    ("LEED Green Associate", "trades"),
    ("Senior Professional in Human Resources (SPHR)", "hr"),
    ("Licensed Professional Counselor", "health"),
    ("Certified Personal Trainer", "fitness"),
    ("Google Ads Display Certification", "sales_mkt"),
    ("Real Estate Salesperson", "fin"),
    ("Ask Questions to Make Data-Driven Decisions", "data"),
    ("Certified Nursing Assistant", "health"),
    ("BLS", "health"),
    ("SHRM-SCP", "hr"),
    ("ACLS", "health"),
    ("Scrum: The Basics", "pm"),
    ("Six Sigma Yellow Belt", "pm"),
    ("Google Analytics for Beginners", "sales_mkt"),
    ("Google AI Essentials", "data"),
    ("ServSafe Food Handler", "food"),
    ("Agile Project Management", "pm"),
    ("Certified Professional Coder (CPC)", "health"),
    ("Security+", "it_sec"),
    ("Google Project Management Certificate", "pm"),
    ("Enterprise Design Thinking Practitioner", "design"),
    ("OSHA 10-Hour", "trades"),
    ("Foundations of User Experience (UX) Design", "design"),
    ("Certified Financial Planner (CFP)", "fin"),
    ("Six Sigma Black Belt", "pm"),
    ("Certified Fraud Examiner (CFE)", "fin"),
    ("Digital Marketing", "sales_mkt"),
    ("Registered Nurse (RN)", "health"),
    ("Real Estate Sales Associate", "fin"),
    ("Generative AI Overview for Project Managers", "pm"),
    ("CCNA", "it_net"),
    ("Property and Casualty Insurance License", "fin"),
    ("Communicating with Confidence", "mgmt"),
    ("Certified Information Systems Auditor (CISA)", "it_sec"),
    ("ITIL Foundation Level", "it_net"),
    ("Communication Foundations", "mgmt"),
    ("SPHR", "hr"),
    ("Six Sigma Foundations", "pm"),
    ("Effective Listening", "mgmt"),
    ("Project Planning: Putting It All Together", "pm"),
    ("Excel Essential Training (Office 365/Microsoft 365)", "data"),
    ("Speaking Confidently and Effectively", "mgmt"),
    ("Inbound Marketing", "sales_mkt"),
    ("Google Data Analytics Certificate", "data"),
    ("OSHA 30", "trades"),
    ("Critical Thinking", "mgmt"),
    ("Registered Behavior Technician (RBT)", "health"),
    ("Certified Personal Trainer (NASM-CPT)", "fitness"),
    ("Email Marketing", "sales_mkt"),
    ("Emergency Medical Technician", "health"),
    ("Prepare Data for Exploration", "data"),
    ("Google Data Analytics Specialization", "data"),
    ("Content Marketing", "sales_mkt"),
    ("Associate Certified Coach (ACC)", "mgmt"),
    ("COVID-19 Contact Tracing", "health"),
    ("Interpersonal Communication", "mgmt"),
    ("Lean Six Sigma Foundations", "pm"),
    ("Microsoft Certified: Azure Administrator Associate", "it_cloud"),
    ("Emergency Medical Technician (EMT)", "health"),
    ("AWS Certified Solutions Architect", "it_cloud"),
    ("Coaching Skills for Leaders and Managers", "mgmt"),
    ("Machine Learning", "data"),
    ("OSHA 30-Hour Construction", "trades"),
    ("Standard First Aid, CPR and AED", "health"),
    ("Microsoft Certified: Azure AI Fundamentals", "it_cloud"),
    ("SQL Essential Training", "data"),
    ("The Bits and Bytes of Computer Networking", "it_net"),
    ("Salesforce Certified Platform Developer I", "swdev"),
    ("Foundations of Cybersecurity", "it_sec"),
    ("Pharmacist", "health"),
    ("Programming for Everybody (Getting Started with Python)", "swdev"),
    ("Certified SAFe® 5 Agilist", "pm"),
    ("Licensed Master Social Worker", "health"),
    ("Professional Scrum Master™ I (PSM I)", "pm"),
    ("Building Resilience", "mgmt"),
    ("Series 79", "fin"),
    ("Engineer In Training", "trades"),
    ("Advanced Google Analytics", "sales_mkt"),
    ("Honored Listee", "other"),
    ("Series 24", "fin"),
    ("Neonatal Resuscitation Program", "health"),
    ("Salesforce Essential Training", "swdev"),
    ("Improving Your Listening Skills", "mgmt"),
    ("Basic Life Support", "health"),
    ("Career Essentials in Generative AI by Microsoft and LinkedIn", "data"),
    ("Real Estate Agent", "fin"),
    ("First Aid", "health"),
    ("Google Data Analytics Professional Certificate", "data"),
    ("Realtor", "fin"),
    ("OSHA 10", "trades"),
    ("Certified Internal Auditor (CIA)", "fin"),
    ("Critical Thinking for Better Judgment and Decision-Making", "mgmt"),
    ("Youth Mental Health First Aid", "health"),
    ("SEO Foundations", "sales_mkt"),
    ("Microsoft Certified Professional", "it_net"),
    ("Process Data from Dirty to Clean", "data"),
    ("Excel: PivotTables for Beginners", "data"),
    ("Professional Scrum Master I", "pm"),
    ("Verified International Academic Qualifications", "other"),
    ("Real Estate License", "fin"),
    ("Cisco Certified Network Associate Routing and Switching (CCNA)", "it_net"),
    ("Foundations of Digital Marketing and E-commerce", "sales_mkt"),
    ("Jodi Glickman on Pitching Yourself", "mgmt"),
    ("Strategic Human Resources", "hr"),
    ("Being an Effective Team Member", "mgmt"),
    ("Open Water Diver", "other"),
    ("Python Data Structures", "swdev"),
    ("Communicating about Culturally Sensitive Issues", "hr"),
    ("Google IT Support Specialization", "it_net"),
    ("Certified Case Manager", "health"),
    ("Time Management: Working from Home", "mgmt"),
    ("Certified Nurse Assistant", "health"),
    ("Adult First Aid/CPR/AED", "health"),
    ("NMLS", "fin"),
    ("Network+", "it_net"),
    ("Chartered Property Casualty Underwriter (CPCU)", "fin"),
    ("Business Analysis Foundations", "data"),
    ("Project Management Skills for Leaders", "pm"),
    ("CompTIA Project+", "pm"),
    ("Leading with Emotional Intelligence", "mgmt"),
    ("Power BI Essential Training", "data"),
    ("Operational Excellence Foundations", "pm"),
    ("PMI Agile Certified Practitioner (PMI-ACP)", "pm"),
    ("Leadership Foundations", "mgmt"),
    ("Customer Service Foundations", "sales_mkt"),
    ("Social and Behavioral Research", "other"),
    ("Certified Ethical Hacker (CEH)", "it_sec"),
    ("CompTIA Cybersecurity Analyst (CySA+)", "it_sec"),
    ("CISSP", "it_sec"),
    ("Professional Certified Coach (PCC)", "mgmt"),
    ("Insurance Agent (Health, Property, Casualty)", "fin"),
    ("Pharmacy Technician", "health"),
    ("Social Media Marketing Foundations", "sales_mkt"),
    ("Instructional Design: Adult Learners", "edu"),
    ("Skills for Inclusive Conversations", "hr"),
    ("Certified Meeting Professional (CMP)", "mgmt"),
    ("AWS Certified Developer – Associate", "it_cloud"),
    ("Time Management Fundamentals", "mgmt"),
    ("The Fundamentals of Digital Marketing", "sales_mkt"),
    ("Problem Solving", "mgmt"),
    ("Microsoft Teams Essential Training", "it_net"),
    ("Scrum Fundamentals Certified (SFC)", "pm"),
    ("Coaching and Developing Employees", "mgmt"),
    ("Registered Architect", "other"),
    ("ServSafe", "food"),
    ("Certified Phlebotomy Technician (CPT)", "health"),
    ("Wilderness First Responder", "health"),
    ("Operating Systems and You: Becoming a Power User", "it_net"),
    ("Change Management Foundations", "mgmt"),
    ("Registered Pharmacist", "health"),
    ("Google Data Analytics", "data"),
    ("IT Information Library Foundations Certification (ITIL)", "it_net"),
    ("Generative AI for Business Leaders", "data"),
    ("Neural Networks and Deep Learning", "data"),
    ("Business Strategy", "mgmt"),
    ("CPR/AED", "health"),
    ("First Aid/CPR/AED Instructor", "health"),
    ("How to Use LinkedIn Learning", "other"),
    ("Certified Clinical Medical Assistant (CCMA)", "health"),
    ("SEO", "sales_mkt"),
    ("Inclusive Leadership", "hr"),
    ("Play It Safe: Manage Security Risks", "it_sec"),
    ("Inbound Certification", "sales_mkt"),
    ("Digital Marketing Foundations", "sales_mkt"),
    ("Airline Transport Pilot", "other"),
    ("Introduction to Artificial Intelligence", "data"),
    ("HTML Essential Training", "swdev"),
    ("QuickBooks Certification", "fin"),
    ("Introduction to Generative AI", "data"),
    ("Analyze Data to Answer Questions", "data"),
    ("Certified Medical Assistant (CMA)", "health"),
    ("AI For Everyone", "data"),
    ("Certified Fraud Examiner", "fin"),
    ("Project Management Foundations: Requirements", "pm"),
    ("Human Resources Foundations", "hr"),
    ("ITIL Foundation", "it_net"),
    ("Embracing Unexpected Change", "mgmt"),
    ("Tableau Desktop Specialist", "data"),
    ("Microsoft Certified: Azure Data Fundamentals", "it_cloud"),
    ("Adult Mental Health First Aid", "health"),
    ("Teaching English as a Foreign Language (TEFL)", "edu"),
    ("AWS Certified AI Practitioner", "it_cloud"),
    ("Licensed Social Worker", "health"),
    ("Chartered Financial Analyst", "fin"),
    ("Getting Things Done", "mgmt"),
    ("Jira Fundamentals Badge", "pm"),
    ("Fundamentals of Digital Marketing", "sales_mkt"),
    ("Asking Great Sales Questions", "sales_mkt"),
    ("Instructional Design Essentials: Models of ID", "edu"),
    ("Certified Information Security Manager (CISM)", "it_sec"),
    ("Giving and Receiving Feedback", "mgmt"),
    ("Certified in Cybersecurity (CC)", "it_sec"),
    ("Professional Scrum Master", "pm"),
    ("Ken Blanchard on Servant Leadership", "mgmt"),
    ("Licensed Practical Nurse", "health"),
    ("Share Data Through the Art of Visualization", "data"),
    ("Paramedic", "health"),
    ("Certified Strength and Conditioning Specialist (CSCS)", "fitness"),
    ("ITIL", "it_net"),
    ("System Administration and IT Infrastructure Services", "it_net"),
    ("SIE", "fin"),
    ("Academy Accreditation - Generative AI Fundamentals", "data"),
    ("LEED AP", "trades"),
    ("Board Certified Behavior Analyst (BCBA)", "health"),
    ("ServiceNow Certified System Administrator", "it_net"),
    ("Certified Safety Professional (CSP)", "trades"),
    ("Connect and Protect: Networks and Network Security", "it_net"),
    ("Associate in General Insurance (AINS)", "fin"),
    ("Certified in Production and Inventory Management (CPIM)", "pm"),
    ("Influencing Others", "mgmt"),
    ("Data Analysis with R Programming", "data"),
    ("Creating Positive Conversations with Challenging Customers", "sales_mkt"),
    ("Paralegal Certificate", "legal"),
    ("Certified Paralegal (CP)", "legal"),
    ("Responsive Web Design", "swdev"),
    ("Architect", "other"),
    ("Enrolled Agent (EA)", "fin"),
    ("Secret Security Clearance", "other"),
    ("Microsoft Certified: Azure Data Engineer Associate", "it_cloud"),
    ("Start the UX Design Process: Empathize, Define, and Ideate", "design"),
    ("Learning Excel 2019", "data"),
    ("Certified Life Coach", "mgmt"),
    ("Talent Sourcing", "hr"),
    ("SQL for Data Science", "data"),
    ("Certified Supply Chain Professional (CSCP)", "pm"),
    ("Salesforce Certified Sales Cloud Consultant", "swdev"),
    ("Social Marketing Certification", "sales_mkt"),
    ("Customer Success Management Fundamentals", "sales_mkt"),
    ("Introduction to Programming Using Python", "swdev"),
    ("Registered Dietitian", "health"),
    ("R Programming", "swdev"),
    ("Human Resources: Payroll", "hr"),
    ("CFA Institute Charterholder", "fin"),
    ("Google Ads Video Certification", "sales_mkt"),
    ("Body Language for Leaders", "mgmt"),
    ("Diversity Recruiting", "hr"),
    ("Learning Data Analytics", "data"),
    ("Inclusive Mindset", "hr"),
    ("ICAgile Certified Professional", "pm"),
    ("Mortgage Loan Originator", "fin"),
    ("Salesforce Certified AI Associate", "swdev"),
    ("Executive Leadership", "mgmt"),
    ("Creating Your Personal Brand", "mgmt"),
    ("ICF Member Badge", "mgmt"),
    ("Private Aircraft Pilot", "other"),
    ("Communicating with Emotional Intelligence", "mgmt"),
    ("Digital Acumen", "mgmt"),
    ("Microsoft 365 Certified: Fundamentals", "it_net"),
    ("Google Cybersecurity Certificate", "it_sec"),
    ("Prompt Engineering for ChatGPT", "data"),
    ("Administrative Professional Foundations", "mgmt"),
    ("PALS", "health"),
    ("Certified Anti-Money Laundering Specialist (CAMLS)", "fin"),
    ("Train the Trainer", "edu"),
    ("Salesforce Certified Administrator", "swdev"),
    ("Certified SAFe® 5 Practitioner", "pm"),
    ("Leading without Formal Authority", "mgmt"),
    ("Developing Executive Presence", "mgmt"),
    ("Leading at a Distance", "mgmt"),
    ("Be the Manager People Won't Leave", "mgmt"),
)

# Ordered keyword rules for the tail. Needles are written in NORMALIZED space
# (cleanlib.normalize output: lowercase, punctuation stripped -- "Security+"
# becomes "security") and matched as substrings of the space-padded normalized
# title; author a leading/trailing space into a needle wherever a word boundary
# matters. First matching domain wins; specific domains before broad ones.
KEYWORD_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("it_cloud", (" aws ", " azure ", " google cloud ", " cloud practitioner ",
                  " cloud architect ", " cloud computing ", " cloud fundamentals ")),
    ("it_sec", (" cissp ", " cism ", " cyber", " ethical hacker ", " cysa ", " giac ",
                " information security ", " security analyst ", " security essentials ",
                " security fundamentals ", " comptia security ", " network security ",
                " security risk", " security manage")),
    ("pm", (" pmp ", " project manage", " scrum ", " agile ", " six sigma ",
            " kanban ", " prince2 ", " capm ", " pmi ", " supply chain ", " lean ")),
    ("fin", (" series 7 ", " series 6 ", " series 63 ", " series 65 ", " series 66 ",
             " series 79 ", " cpa ", " cfa ", " cfp ", " insurance ", " notary ",
             " real estate ", " mortgage ", " bookkeep", " quickbooks ", " accounting ",
             " finra ", " securities ", " underwrit", " enrolled agent ", " actuar",
             " anti money laundering ", " loan officer ", " tax prepar", " appraiser ")),
    ("health", (" bls ", " acls ", " cpr ", " first aid ", " nurse", " nursing ",
                " emt ", " paramedic ", " phlebotom", " pharmac", " medical ",
                " clinical ", " patient ", " cna ", " dental ", " ekg ",
                " life support ", " behavior analyst ", " social work",
                " mental health ", " counselor ", " counseling ", " dietitian ",
                " nutrition", " caregiver ", " medication ", " hipaa ",
                " healthcare ", " therap")),
    ("data", (" data analy", " analytics ", " sql ", " tableau ", " power bi ",
              " excel ", " machine learning ", " artificial intelligence ",
              " generative ai ", " deep learning ", " statistics ", " big data ",
              " data science ", " data visualization ")),
    ("swdev", (" python ", " javascript ", " java ", " html ", " css ",
               " programming ", " software develop", " web develop", " salesforce ",
               " github ", " coding ", " react ")),
    ("it_net", (" ccna ", " comptia ", " network", " itil ", " microsoft certified ",
                " windows server ", " linux ", " servicenow ", " it support ",
                " help desk ", " system admin", " microsoft 365 ", " cisco ")),
    ("hr", (" shrm ", " sphr ", " phr ", " human resources ", " recruit",
            " talent ", " diversity ", " inclusion ", " payroll ", " onboarding ")),
    ("sales_mkt", (" google ads ", " google analytics ", " marketing ", " seo ",
                   " sales ", " hubspot ", " social media ", " customer service ",
                   " advertis", " e commerce ", " ecommerce ", " crm ")),
    ("edu", (" teach", " tefl ", " tesol ", " instructional ", " montessori ",
             " esl ", " classroom ", " educator ", " substitute ",
             " paraprofessional ")),
    ("trades", (" osha ", " forklift ", " welding ", " hvac ", " electrician",
                " cdl ", " crane ", " construction ", " safety professional ",
                " professional engineer ", " leed ", " asbestos ", " scaffold",
                " confined space ", " flagger ", " security guard ", " guard card ",
                " pesticide ", " backflow ", " journeyman ")),
    ("food", (" servsafe ", " serve safe ", " food handler", " food safety ",
              " food protection ", " alcohol ", " bartend", " mixolog")),
    ("fitness", (" personal train", " yoga ", " fitness ", " nasm ",
                 " strength and conditioning ", " group exercise ", " pilates ",
                 " zumba ", " lifeguard ", " crossfit ")),
    ("legal", (" paralegal ", " legal ", " attorney ", " bar admission ", " mediat")),
    ("lang", (" language ", " spanish ", " french ", " mandarin ", " toefl ",
              " ielts ", " interpreter ", " translat")),
    ("design", (" ux ", " user experience ", " photoshop ", " adobe ",
                " graphic design ", " illustrator ", " indesign ", " figma ",
                " design thinking ")),
    ("mgmt", (" leadership ", " management ", " coaching ", " communication ",
              " emotional intelligence ", " time management ", " business ",
              " entrepreneur", " negotiat", " public speaking ", " productivity ",
              " manager ")),
)

_CURATED: dict[str, str] | None = None


def curated_map() -> dict[str, str]:
    """normalized title -> domain; first-wins on collisions (frequency order)."""
    global _CURATED
    if _CURATED is None:
        m: dict[str, str] = {}
        for raw, dom in CURATED_RAW:
            key = normalize(raw)
            if key and key not in m:
                m[key] = dom
        _CURATED = m
    return _CURATED


def classify(title: str | None) -> tuple[str | None, str | None, float | None]:
    """(domain, method, confidence) for one raw certification title."""
    norm = normalize(title)
    if not norm:
        return None, None, None
    dom = curated_map().get(norm)
    if dom is not None:
        return dom, "curated", 0.97
    padded = f" {norm} "
    for dom, needles in KEYWORD_RULES:
        if any(n in padded for n in needles):
            return dom, "keyword", 0.8
    return None, None, None
